services:
  api:
    image: vasjajj/seamless
#    build:
#      context: .
#      dockerfile: build/Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=seamless
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
